services:
  database_gym:
    image: mysql
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: America/Guayaquil
    ports:
      - "3306:3306"
    volumes:
      - ./Database:/var/lib/mysql
      - ./Resources/gymvitae_db.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    networks:
      - gymvitae_networks

networks:
  gymvitae_networks:
    driver: bridge
    name: gymvitae_networks
