name: Java-Maven-Workflow

on:
  push:
    branches: ["main", "testing"]
  pull_request:
    branches: ["main"]

jobs:
  dependencies-run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: defined sdk
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          architecture: x64
          cache: maven

      - name: Maven install dependencies
        run: mvn clean install --batch-mode --update-snapshots verify
        working-directory: ./App

      - name: run test controllers
        run: mvn test
        working-directory: ./App

      - name: build
        run: mvn clean package
        working-directory: ./App

      - name: upload-jar
        run: mkdir staging && cp -r ./App/target/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging

  realise-jar-actions:
    needs: dependencies-run-tests

    if: ${{success()}}

    runs-on: ubuntu-latest

    steps:
      - name: download binary jar
        uses: actions/download-artifact@v4
        with:
          name: Package
